import { Project, TimeEntry, Client } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Website Redesign',
    client: 'Acme Inc',
    color: 'text-indigo-600',
    hoursUsed: 7.5,
    hoursTotal: 10,
    access: 'Public',
    amount: 'USD 5,000.00',
    isFavorite: true,
  },
  {
    id: 'p2',
    name: 'SEO Audit',
    client: 'Globex Corp',
    color: 'text-purple-600',
    hoursUsed: 18.2,
    hoursTotal: 20,
    access: 'Private',
    amount: 'USD 1,200.00',
    isFavorite: false,
  },
  {
    id: 'p3',
    name: 'Mobile App Dev',
    client: 'Soylent Corp',
    color: 'text-blue-600',
    hoursUsed: 55,
    hoursTotal: 40,
    access: 'Public',
    amount: 'USD 15,000.00',
    isFavorite: true,
  },
  {
    id: 'p4',
    name: 'Maintenance',
    client: 'Umbrella Corp',
    color: 'text-slate-600',
    hoursUsed: 2,
    hoursTotal: 15,
    access: 'Public',
    amount: 'USD 0.00',
    isFavorite: false,
  },
  {
    id: 'p5',
    name: 'Q3 Marketing Assets',
    client: 'Acme Inc',
    color: 'text-emerald-600',
    hoursUsed: 0,
    hoursTotal: 100,
    access: 'Private',
    amount: 'USD 0.00',
    isFavorite: false,
  }
];

export const MOCK_CLIENTS: Client[] = [
  { id: 'c1', name: 'Direct Mail 2.0', currency: 'USD' },
  { id: 'c2', name: 'TXL Films', currency: 'USD' },
  { id: 'c3', name: 'Acme Inc', address: '123 Acme Way, San Francisco, CA', currency: 'EUR' },
  { id: 'c4', name: 'Globex Corp', address: 'Cypress Creek', currency: 'USD' },
];

export const MOCK_TIME_ENTRIES: TimeEntry[] = [
  {
    id: 't1',
    description: 'Fixing Navbar Bugs',
    projectId: 'p1',
    date: '2023-10-27',
    startTime: '09:00 AM',
    endTime: '11:15 AM',
    duration: '02:15:00',
    durationSeconds: 8100,
    isBillable: true,
  },
  {
    id: 't2',
    description: 'Keyword Research',
    projectId: 'p2',
    date: '2023-10-27',
    startTime: '11:30 AM',
    endTime: '12:30 PM',
    duration: '01:00:00',
    durationSeconds: 3600,
    isBillable: true,
  },
  {
    id: 't3',
    description: 'Emergency Server Patch',
    projectId: 'p3',
    date: '2023-10-26',
    startTime: '01:00 PM',
    endTime: '01:45 PM',
    duration: '00:45:00',
    durationSeconds: 2700,
    isBillable: true,
  },
  {
    id: 't4',
    description: 'Client Meeting',
    projectId: 'p1',
    date: '2023-10-26',
    startTime: '02:00 PM',
    endTime: '03:00 PM',
    duration: '01:00:00',
    durationSeconds: 3600,
    isBillable: false,
  },
  {
    id: 't5',
    description: 'Database Migration',
    projectId: 'p3',
    date: '2023-10-26',
    startTime: '04:00 PM',
    endTime: '06:30 PM',
    duration: '02:30:00',
    durationSeconds: 9000,
    isBillable: true,
  },
];